## sonar.projectKey=jiancha
## sonar.projectName=Jiancha Car Rental

sonar.projectKey=WarutSun_2025-ITCS383-JianCha
sonar.organization=warutsun
sonar.projectVersion=1.0

sonar.sources=implementations/backend/src
sonar.tests=implementations/backend/tests

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=sqp_53f03f1f3c11ad27ddf401f9b7b686cf5e899a30

sonar.javascript.lcov.reportPaths=implementations/backend/coverage/lcov.info
