sonar.projectKey=Jiancha
sonar.projectName=jianCha
sonar.projectVersion=1.0

sonar.sources=implementations
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.login=sqp_b1f039928ed14513a15f9bf268ce73f3591a745b